"""
Init command for Invar.

Shell module: handles project initialization.
DX-21B: Added --claude flag for Claude Code integration.
DX-55: Unified idempotent init command with smart merge.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import typer
from returns.result import Failure, Success
from rich.console import Console

from invar.core.template_parser import ClaudeMdState
from invar.shell.commands.merge import (
    ProjectState,
    detect_project_state,
    merge_claude_md,
)
from invar.shell.mcp_config import (
    detect_available_methods,
    generate_mcp_json,
    get_method_by_name,
    get_recommended_method,
)
from invar.shell.template_engine import generate_from_manifest
from invar.shell.templates import (
    add_config,
    add_invar_reference,
    create_agent_config,
    create_directories,
    detect_agent_configs,
    install_hooks,
)

console = Console()


# @shell_complexity: Claude init with config file detection
def run_claude_init(path: Path) -> bool:
    """
    Run 'claude /init' to generate intelligent CLAUDE.md.

    Returns True if successful, False otherwise.
    """
    if not shutil.which("claude"):
        console.print(
            "[yellow]Warning:[/yellow] 'claude' CLI not found. "
            "Install Claude Code: https://claude.ai/code"
        )
        console.print("[dim]Skipping claude /init, will create basic CLAUDE.md[/dim]")
        return False

    console.print("\n[bold]Running claude /init...[/bold]")
    try:
        result = subprocess.run(
            ["claude", "/init"],
            cwd=path,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0:
            console.print("[green]claude /init completed successfully[/green]")
            return True
        else:
            console.print(f"[yellow]Warning:[/yellow] claude /init failed: {result.stderr}")
            return False
    except subprocess.TimeoutExpired:
        console.print("[yellow]Warning:[/yellow] claude /init timed out")
        return False
    except Exception as e:
        console.print(f"[yellow]Warning:[/yellow] claude /init error: {e}")
        return False


def append_invar_reference_to_claude_md(path: Path) -> bool:
    """
    Append Invar reference to existing CLAUDE.md.

    Preserves content generated by 'claude /init'.
    Returns True if modified, False otherwise.
    """
    claude_md = path / "CLAUDE.md"
    if not claude_md.exists():
        return False

    content = claude_md.read_text()
    if "INVAR.md" in content:
        console.print("[dim]CLAUDE.md already references INVAR.md[/dim]")
        return False

    # Append reference at the end
    invar_reference = """

---

## Invar Protocol

> **Protocol:** Follow [INVAR.md](./INVAR.md) — includes Check-In, USBV workflow, and Task Completion.

### Check-In

Your first message MUST display:

```
✓ Check-In: guard PASS | top: <entry1>, <entry2>
```

Execute `invar guard --changed` and `invar map --top 10`, then show this one-line summary.

### Final

Your last message MUST display:

```
✓ Final: guard PASS | 0 errors, 2 warnings
```

Execute `invar guard` and show this one-line summary.
"""

    claude_md.write_text(content + invar_reference)
    console.print("[green]Updated[/green] CLAUDE.md (added Invar reference)")
    return True


# @shell_complexity: MCP config with method selection and validation
def configure_mcp_with_method(
    path: Path, mcp_method: str | None
) -> None:
    """Configure MCP server with specified or detected method."""
    import json

    # Determine method to use
    if mcp_method:
        config = get_method_by_name(mcp_method)
        if config is None:
            console.print(f"[yellow]Warning:[/yellow] Method '{mcp_method}' not available")
            config = get_recommended_method()
            console.print(f"[dim]Using fallback: {config.description}[/dim]")
    else:
        config = get_recommended_method()

    console.print("\n[bold]Configuring MCP server...[/bold]")
    console.print(f"  Method: {config.description}")

    # Generate and write .mcp.json
    mcp_json_path = path / ".mcp.json"
    mcp_content = generate_mcp_json(config)

    if mcp_json_path.exists():
        try:
            existing = json.loads(mcp_json_path.read_text())
            if "mcpServers" in existing and "invar" in existing.get("mcpServers", {}):
                console.print("[dim]Skipped[/dim] .mcp.json (invar already configured)")
                return
            # Add invar to existing config
            if "mcpServers" not in existing:
                existing["mcpServers"] = {}
            existing["mcpServers"]["invar"] = mcp_content["mcpServers"]["invar"]
            mcp_json_path.write_text(json.dumps(existing, indent=2))
            console.print("[green]Updated[/green] .mcp.json (added invar)")
        except (json.JSONDecodeError, OSError):
            console.print("[yellow]Warning:[/yellow] .mcp.json exists but couldn't update")
    else:
        mcp_json_path.write_text(json.dumps(mcp_content, indent=2))
        console.print("[green]Created[/green] .mcp.json")


def show_available_mcp_methods() -> None:
    """Display available MCP execution methods."""
    methods = detect_available_methods()
    console.print("\n[bold]Available MCP methods:[/bold]")
    for i, method in enumerate(methods):
        marker = "[green]→[/green]" if i == 0 else " "
        console.print(f"  {marker} {method.method.value}: {method.description}")


# @shell_complexity: Project init with config detection and template setup
def init(
    path: Path = typer.Argument(Path(), help="Project root directory"),
    claude: bool = typer.Option(
        False, "--claude", help="Run 'claude /init' and integrate with Claude Code"
    ),
    mcp_method: str = typer.Option(
        None,
        "--mcp-method",
        help="MCP execution method: uvx (recommended), command, or python",
    ),
    dirs: bool = typer.Option(
        None, "--dirs/--no-dirs", help="Create src/core and src/shell directories"
    ),
    hooks: bool = typer.Option(
        True, "--hooks/--no-hooks", help="Install pre-commit hooks (default: ON)"
    ),
    skills: bool = typer.Option(
        True, "--skills/--no-skills", help="Create .claude/skills/ (default: ON, use --no-skills for Cursor)"
    ),
    yes: bool = typer.Option(
        False, "--yes", "-y", help="Accept defaults without prompting"
    ),
    check: bool = typer.Option(
        False, "--check", help="Preview changes without applying (DX-55)"
    ),
    force: bool = typer.Option(
        False, "--force", help="Update even if already current (DX-55)"
    ),
    reset: bool = typer.Option(
        False, "--reset", help="Dangerous: discard all user content (DX-55)"
    ),
) -> None:
    """
    Initialize or update Invar configuration (idempotent).

    DX-55: This command is idempotent - safe to run multiple times.
    It detects current state and does the right thing:

    \b
    - New project: Full setup
    - Existing project: Update managed regions, preserve user content
    - Corrupted/overwritten: Smart recovery with content preservation

    Works with or without pyproject.toml:

    \b
    - If pyproject.toml exists: adds tool.invar section
    - Otherwise: creates invar.toml

    Use --check to preview changes without applying.
    Use --force to update even if already current.
    Use --reset to discard all user content (dangerous).
    Use --claude to run 'claude /init' first.
    Use --mcp-method to specify MCP execution method (uvx, command, python).
    Use --dirs to always create directories, --no-dirs to skip.
    Use --no-hooks to skip pre-commit hooks installation.
    Use --no-skills to skip .claude/skills/ creation (for Cursor users).
    Use --yes to accept defaults without prompting.
    """
    from invar import __version__

    # DX-55: Detect project state first
    state = detect_project_state(path)

    # --check mode: preview only
    if check:
        _show_check_preview(state, path, __version__)
        return

    # --reset mode: dangerous full reset
    if reset:
        if not yes and not typer.confirm(
            "[red]This will DELETE all user customizations. Continue?[/red]",
            default=False,
        ):
            console.print("[yellow]Cancelled[/yellow]")
            return
        # Fall through to full init with reset flag
        state = ProjectState(
            initialized=False,
            claude_md_state=ClaudeMdState(state="absent"),
            version="",
            needs_update=True,
        )

    # DX-55: Handle based on detected state
    action = state.action if not force else "update"

    if action == "none" and not force:
        # DX-55: Check for missing required files before declaring "no changes needed"
        missing_files = []
        if skills:
            skill_files = [
                ".claude/skills/develop/SKILL.md",
                ".claude/skills/investigate/SKILL.md",
                ".claude/skills/propose/SKILL.md",
                ".claude/skills/review/SKILL.md",
            ]
            for skill_file in skill_files:
                if not (path / skill_file).exists():
                    missing_files.append(skill_file)

        if not missing_files:
            console.print(f"[green]✓[/green] Invar v{__version__} configured (no changes needed)")
            console.print("[dim]Use --force to refresh managed regions[/dim]")
            return
        else:
            # Recreate missing files
            console.print(f"[yellow]Detected:[/yellow] {len(missing_files)} missing file(s)")
            result = generate_from_manifest(path, syntax="cli", files_to_generate=missing_files)
            if isinstance(result, Success):
                for generated_file in result.unwrap():
                    console.print(f"[green]Restored[/green] {generated_file}")
            console.print(f"[green]✓[/green] Invar v{__version__} configured")
            return

    if action == "recover":
        console.print(f"\n[yellow]Detected:[/yellow] CLAUDE.md {state.claude_md_state.state} state")
        console.print("[bold]Recovering Invar configuration...[/bold]")
        merge_result = merge_claude_md(path, state.claude_md_state)
        if isinstance(merge_result, Success):
            action_name = merge_result.unwrap()
            console.print(f"[green]✓[/green] CLAUDE.md {action_name}")
            if action_name == "merged":
                console.print("[dim]Review the merged content in CLAUDE.md[/dim]")
        else:
            console.print(f"[yellow]Warning:[/yellow] {merge_result.failure()}")

    # DX-55: Handle full_init with existing CLAUDE.md (A2 scenario)
    if action == "full_init":
        claude_md = path / "CLAUDE.md"
        if claude_md.exists():
            content = claude_md.read_text()
            if content.strip() and "<!--invar:" not in content:
                # Existing content without Invar regions - merge it
                console.print("[yellow]Detected:[/yellow] Existing CLAUDE.md without Invar regions")
                console.print("[bold]Merging existing content...[/bold]")
                from invar.core.template_parser import ClaudeMdState as CMS
                merge_result = merge_claude_md(path, CMS(state="missing"))
                if isinstance(merge_result, Success):
                    console.print(f"[green]✓[/green] CLAUDE.md {merge_result.unwrap()}")
            elif not content.strip():
                # Empty file - delete so generate_from_manifest can create it
                claude_md.unlink()

    # DX-55: Handle "create" action (empty CLAUDE.md exists)
    if action == "create":
        claude_md = path / "CLAUDE.md"
        if claude_md.exists() and not claude_md.read_text().strip():
            # Empty file - delete so generate_from_manifest can create it
            claude_md.unlink()

    # DX-21B: Run claude /init if requested
    if claude:
        claude_success = run_claude_init(path)
        if claude_success:
            # Append Invar reference to generated CLAUDE.md
            append_invar_reference_to_claude_md(path)

    config_result = add_config(path, console)
    if isinstance(config_result, Failure):
        console.print(f"[red]Error:[/red] {config_result.failure()}")
        raise typer.Exit(1)
    config_added = config_result.unwrap()

    # DX-49: Generate files from manifest (CLI syntax for external projects)
    console.print("\n[bold]Creating Invar files...[/bold]")
    init_files = [
        "INVAR.md",
        ".invar/context.md",
        ".invar/examples/",
        ".pre-commit-config.yaml",
        ".claude/commands/audit.md",
        ".claude/commands/guard.md",
    ]

    # Skills define the workflow - optional for non-Claude editors (e.g., Cursor)
    if skills:
        init_files.extend([
            ".claude/skills/develop/SKILL.md",
            ".claude/skills/investigate/SKILL.md",
            ".claude/skills/propose/SKILL.md",
            ".claude/skills/review/SKILL.md",
        ])

    # DX-55: Create CLAUDE.md if not already handled by recovery
    # Also handles case where binary content was deleted during recovery
    if not (path / "CLAUDE.md").exists():
        init_files.append("CLAUDE.md")

    result = generate_from_manifest(path, syntax="cli", files_to_generate=init_files)
    if isinstance(result, Success):
        for generated_file in result.unwrap():
            console.print(f"[green]Created[/green] {generated_file}")
    else:
        console.print(f"[yellow]Warning:[/yellow] {result.failure()}")

    # Create .invar directory structure (for proposals template - not in manifest)
    invar_dir = path / ".invar"
    if not invar_dir.exists():
        invar_dir.mkdir()

    # Create proposals directory for protocol governance
    proposals_dir = invar_dir / "proposals"
    if not proposals_dir.exists():
        proposals_dir.mkdir()
        from invar.shell.templates import copy_template
        result = copy_template("proposal.md.template", proposals_dir, "TEMPLATE.md")
        if isinstance(result, Success) and result.unwrap():
            console.print("[green]Created[/green] .invar/proposals/TEMPLATE.md")

    # Agent detection and configuration (DX-11)
    console.print("\n[bold]Checking for agent configurations...[/bold]")
    agent_result = detect_agent_configs(path)
    if isinstance(agent_result, Failure):
        console.print(f"[yellow]Warning:[/yellow] {agent_result.failure()}")
        agent_status: dict[str, str] = {}
    else:
        agent_status = agent_result.unwrap()

    # Handle agent configs (DX-11, DX-17)
    for agent, status in agent_status.items():
        if status == "configured":
            console.print(f"  [green]✓[/green] {agent}: already configured")
        elif status == "found":
            # Existing file without Invar reference - ask before modifying
            if yes or typer.confirm(f"  Add Invar reference to {agent} config?", default=True):
                add_invar_reference(path, agent, console)
            else:
                console.print(f"  [yellow]○[/yellow] {agent}: skipped")
        elif status == "not_found":
            # Create full template with workflow enforcement (DX-17)
            create_agent_config(path, agent, console)

    # Configure MCP server (DX-16, DX-21B)
    configure_mcp_with_method(path, mcp_method)

    # Show available methods if user might want to change
    if not mcp_method and not yes:
        show_available_mcp_methods()

    # Create MCP setup guide
    mcp_setup = invar_dir / "mcp-setup.md"
    if not mcp_setup.exists():
        from invar.shell.templates import _MCP_SETUP_TEMPLATE
        mcp_setup.write_text(_MCP_SETUP_TEMPLATE)
        console.print("[green]Created[/green] .invar/mcp-setup.md (setup guide)")

    # Handle directory creation based on --dirs flag
    if dirs is not False:
        create_directories(path, console)

    # Install pre-commit hooks if requested
    if hooks:
        install_hooks(path, console)

    if not config_added and not (path / "INVAR.md").exists():
        console.print("[yellow]Invar already configured.[/yellow]")

    # DX-55: Summary based on action taken
    if action == "full_init":
        console.print(f"\n[bold green]✓ Initialized Invar v{__version__}[/bold green]")
        console.print("[dim]Note: If you run 'claude /init' later, just run 'invar init' again.[/dim]")
    elif action == "recover":
        console.print(f"\n[bold green]✓ Recovered Invar v{__version__}[/bold green]")
        console.print("[dim]Review the merged content in CLAUDE.md[/dim]")
    elif action == "update" or force:
        console.print(f"\n[bold green]✓ Updated Invar v{__version__}[/bold green]")
        console.print("[dim]Refreshed managed regions, preserved user content[/dim]")
    else:
        console.print("\n[bold green]Invar initialized successfully![/bold green]")

    if claude:
        console.print("[dim]Next: Review CLAUDE.md and start coding with Claude Code[/dim]")


# @shell_complexity: Preview display requires multiple state-specific branches
def _show_check_preview(state: ProjectState, path: Path, version: str) -> None:
    """Show preview of what would change (--check mode)."""
    console.print(f"\n[bold]Invar v{version} - Preview Mode[/bold]\n")

    console.print(f"Project state: [cyan]{state.claude_md_state.state}[/cyan]")
    console.print(f"Initialized: [cyan]{state.initialized}[/cyan]")
    console.print(f"Current version: [cyan]{state.version or 'N/A'}[/cyan]")
    console.print(f"Needs update: [cyan]{state.needs_update}[/cyan]")
    console.print(f"Action: [cyan]{state.action}[/cyan]\n")

    match state.action:
        case "none":
            console.print("[green]No changes needed[/green]")
        case "full_init":
            console.print("Would create:")
            console.print("  - INVAR.md")
            console.print("  - CLAUDE.md")
            console.print("  - .invar/context.md")
            console.print("  - .claude/skills/")
            console.print("  - .pre-commit-config.yaml")
        case "update":
            console.print("Would update:")
            console.print(f"  - CLAUDE.md (managed section v{state.version} → v{version})")
            console.print("  - .claude/skills/* (refresh)")
        case "recover":
            console.print("[yellow]Would recover:[/yellow]")
            console.print("  - CLAUDE.md (restore regions, preserve content)")
        case "create":
            console.print("Would create:")
            console.print("  - CLAUDE.md")

    console.print("\n[dim]Run 'invar init' to apply.[/dim]")
