"""
Init command for Invar.

Shell module: handles project initialization.
DX-21B: Added --claude flag for Claude Code integration.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import typer
from returns.result import Failure, Success
from rich.console import Console

from invar.shell.mcp_config import (
    detect_available_methods,
    generate_mcp_json,
    get_method_by_name,
    get_recommended_method,
)
from invar.shell.template_engine import generate_from_manifest
from invar.shell.templates import (
    add_config,
    add_invar_reference,
    create_agent_config,
    create_directories,
    detect_agent_configs,
    install_hooks,
)

console = Console()


# @shell_complexity: Claude init with config file detection
def run_claude_init(path: Path) -> bool:
    """
    Run 'claude /init' to generate intelligent CLAUDE.md.

    Returns True if successful, False otherwise.
    """
    if not shutil.which("claude"):
        console.print(
            "[yellow]Warning:[/yellow] 'claude' CLI not found. "
            "Install Claude Code: https://claude.ai/code"
        )
        console.print("[dim]Skipping claude /init, will create basic CLAUDE.md[/dim]")
        return False

    console.print("\n[bold]Running claude /init...[/bold]")
    try:
        result = subprocess.run(
            ["claude", "/init"],
            cwd=path,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode == 0:
            console.print("[green]claude /init completed successfully[/green]")
            return True
        else:
            console.print(f"[yellow]Warning:[/yellow] claude /init failed: {result.stderr}")
            return False
    except subprocess.TimeoutExpired:
        console.print("[yellow]Warning:[/yellow] claude /init timed out")
        return False
    except Exception as e:
        console.print(f"[yellow]Warning:[/yellow] claude /init error: {e}")
        return False


def append_invar_reference_to_claude_md(path: Path) -> bool:
    """
    Append Invar reference to existing CLAUDE.md.

    Preserves content generated by 'claude /init'.
    Returns True if modified, False otherwise.
    """
    claude_md = path / "CLAUDE.md"
    if not claude_md.exists():
        return False

    content = claude_md.read_text()
    if "INVAR.md" in content:
        console.print("[dim]CLAUDE.md already references INVAR.md[/dim]")
        return False

    # Append reference at the end
    invar_reference = """

---

## Invar Protocol

> **Protocol:** Follow [INVAR.md](./INVAR.md) — includes Check-In, USBV workflow, and Task Completion.

### Check-In

Your first message MUST display:

```
✓ Check-In: guard PASS | top: <entry1>, <entry2>
```

Execute `invar guard --changed` and `invar map --top 10`, then show this one-line summary.

### Final

Your last message MUST display:

```
✓ Final: guard PASS | 0 errors, 2 warnings
```

Execute `invar guard` and show this one-line summary.
"""

    claude_md.write_text(content + invar_reference)
    console.print("[green]Updated[/green] CLAUDE.md (added Invar reference)")
    return True


# @shell_complexity: MCP config with method selection and validation
def configure_mcp_with_method(
    path: Path, mcp_method: str | None
) -> None:
    """Configure MCP server with specified or detected method."""
    import json

    # Determine method to use
    if mcp_method:
        config = get_method_by_name(mcp_method)
        if config is None:
            console.print(f"[yellow]Warning:[/yellow] Method '{mcp_method}' not available")
            config = get_recommended_method()
            console.print(f"[dim]Using fallback: {config.description}[/dim]")
    else:
        config = get_recommended_method()

    console.print("\n[bold]Configuring MCP server...[/bold]")
    console.print(f"  Method: {config.description}")

    # Generate and write .mcp.json
    mcp_json_path = path / ".mcp.json"
    mcp_content = generate_mcp_json(config)

    if mcp_json_path.exists():
        try:
            existing = json.loads(mcp_json_path.read_text())
            if "mcpServers" in existing and "invar" in existing.get("mcpServers", {}):
                console.print("[dim]Skipped[/dim] .mcp.json (invar already configured)")
                return
            # Add invar to existing config
            if "mcpServers" not in existing:
                existing["mcpServers"] = {}
            existing["mcpServers"]["invar"] = mcp_content["mcpServers"]["invar"]
            mcp_json_path.write_text(json.dumps(existing, indent=2))
            console.print("[green]Updated[/green] .mcp.json (added invar)")
        except (json.JSONDecodeError, OSError):
            console.print("[yellow]Warning:[/yellow] .mcp.json exists but couldn't update")
    else:
        mcp_json_path.write_text(json.dumps(mcp_content, indent=2))
        console.print("[green]Created[/green] .mcp.json")


def show_available_mcp_methods() -> None:
    """Display available MCP execution methods."""
    methods = detect_available_methods()
    console.print("\n[bold]Available MCP methods:[/bold]")
    for i, method in enumerate(methods):
        marker = "[green]→[/green]" if i == 0 else " "
        console.print(f"  {marker} {method.method.value}: {method.description}")


# @shell_complexity: Project init with config detection and template setup
def init(
    path: Path = typer.Argument(Path(), help="Project root directory"),
    claude: bool = typer.Option(
        False, "--claude", help="Run 'claude /init' and integrate with Claude Code"
    ),
    mcp_method: str = typer.Option(
        None,
        "--mcp-method",
        help="MCP execution method: uvx (recommended), command, or python",
    ),
    dirs: bool = typer.Option(
        None, "--dirs/--no-dirs", help="Create src/core and src/shell directories"
    ),
    hooks: bool = typer.Option(
        True, "--hooks/--no-hooks", help="Install pre-commit hooks (default: ON)"
    ),
    yes: bool = typer.Option(
        False, "--yes", "-y", help="Accept defaults without prompting"
    ),
) -> None:
    """
    Initialize Invar configuration in a project.

    Works with or without pyproject.toml:

    \b
    - If pyproject.toml exists: adds tool.invar section
    - Otherwise: creates invar.toml

    Use --claude to run 'claude /init' first (recommended for Claude Code users).
    Use --mcp-method to specify MCP execution method (uvx, command, python).
    Use --dirs to always create directories, --no-dirs to skip.
    Use --no-hooks to skip pre-commit hooks installation.
    Use --yes to accept defaults without prompting.
    """
    # DX-21B: Run claude /init if requested
    if claude:
        claude_success = run_claude_init(path)
        if claude_success:
            # Append Invar reference to generated CLAUDE.md
            append_invar_reference_to_claude_md(path)

    config_result = add_config(path, console)
    if isinstance(config_result, Failure):
        console.print(f"[red]Error:[/red] {config_result.failure()}")
        raise typer.Exit(1)
    config_added = config_result.unwrap()

    # DX-49: Generate files from manifest (CLI syntax for external projects)
    console.print("\n[bold]Creating Invar files...[/bold]")
    init_files = [
        "INVAR.md",
        ".invar/context.md",
        ".invar/examples/",
        ".pre-commit-config.yaml",
        ".claude/commands/audit.md",
        ".claude/commands/guard.md",
    ]

    # Only create CLAUDE.md from template if claude /init wasn't run
    if not claude or not (path / "CLAUDE.md").exists():
        init_files.append("CLAUDE.md")

    # Generate skills if --claude flag
    if claude:
        init_files.extend([
            ".claude/skills/develop/SKILL.md",
            ".claude/skills/investigate/SKILL.md",
            ".claude/skills/propose/SKILL.md",
            ".claude/skills/review/SKILL.md",
        ])

    result = generate_from_manifest(path, syntax="cli", files_to_generate=init_files)
    if isinstance(result, Success):
        for generated_file in result.unwrap():
            console.print(f"[green]Created[/green] {generated_file}")
    else:
        console.print(f"[yellow]Warning:[/yellow] {result.failure()}")

    # Create .invar directory structure (for proposals template - not in manifest)
    invar_dir = path / ".invar"
    if not invar_dir.exists():
        invar_dir.mkdir()

    # Create proposals directory for protocol governance
    proposals_dir = invar_dir / "proposals"
    if not proposals_dir.exists():
        proposals_dir.mkdir()
        from invar.shell.templates import copy_template
        result = copy_template("proposal.md.template", proposals_dir, "TEMPLATE.md")
        if isinstance(result, Success) and result.unwrap():
            console.print("[green]Created[/green] .invar/proposals/TEMPLATE.md")

    # Agent detection and configuration (DX-11)
    console.print("\n[bold]Checking for agent configurations...[/bold]")
    agent_result = detect_agent_configs(path)
    if isinstance(agent_result, Failure):
        console.print(f"[yellow]Warning:[/yellow] {agent_result.failure()}")
        agent_status: dict[str, str] = {}
    else:
        agent_status = agent_result.unwrap()

    # Handle agent configs (DX-11, DX-17)
    for agent, status in agent_status.items():
        if status == "configured":
            console.print(f"  [green]✓[/green] {agent}: already configured")
        elif status == "found":
            # Existing file without Invar reference - ask before modifying
            if yes or typer.confirm(f"  Add Invar reference to {agent} config?", default=True):
                add_invar_reference(path, agent, console)
            else:
                console.print(f"  [yellow]○[/yellow] {agent}: skipped")
        elif status == "not_found":
            # Create full template with workflow enforcement (DX-17)
            create_agent_config(path, agent, console)

    # Configure MCP server (DX-16, DX-21B)
    configure_mcp_with_method(path, mcp_method)

    # Show available methods if user might want to change
    if not mcp_method and not yes:
        show_available_mcp_methods()

    # Create MCP setup guide
    mcp_setup = invar_dir / "mcp-setup.md"
    if not mcp_setup.exists():
        from invar.shell.templates import _MCP_SETUP_TEMPLATE
        mcp_setup.write_text(_MCP_SETUP_TEMPLATE)
        console.print("[green]Created[/green] .invar/mcp-setup.md (setup guide)")

    # Handle directory creation based on --dirs flag
    if dirs is not False:
        create_directories(path, console)

    # Install pre-commit hooks if requested
    if hooks:
        install_hooks(path, console)

    if not config_added and not (path / "INVAR.md").exists():
        console.print("[yellow]Invar already configured.[/yellow]")

    # Summary
    console.print("\n[bold green]Invar initialized successfully![/bold green]")
    if claude:
        console.print("[dim]Next: Review CLAUDE.md and start coding with Claude Code[/dim]")
    else:
        console.print("[dim]Tip: Use --claude for Claude Code integration[/dim]")
